windows:
  hosts:
  children:
    servers:
      hosts:
        10.0.5.5:
          hostname: dc-blue8
        10.0.5.6:
          hostname: fs-blue8
    workstations:
      hosts:
        10.0.5.89:
          hostname: ws1-blue8
        10.0.5.88:
          hostname: ws2-blue8

  vars:
    ansible_user: deployer
    device: Ethernet0
    netmask: 255.255.255.0
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue8.local
    ansible_shell_type: powershell