- name: Join to Blue Team Domain
  hosts: workstations
  gather_facts: no
  vars_prompt:
    - name: domainadminuser
      prompt: "Domain Admin User"
      private: no
    - name: domainadminpass
      prompt: "Domain Admin Password"
      private: yes  

  tasks:
    - name: change hostname
      win_hostname:
        name: "{{ hostname }}"
      register: res

    - name: Reboot after rename
      when: res.reboot_required
      win_reboot:
        msg: "Renaming in process; rebooting..."
        # Tests to see if Server Core is back up
        test_command: 'hostname'

    - name: Change DNS Server to blue8-dc
      win_shell:
        netsh interface ip set dns name="{{ device }}" static "{{ name_server }}"

    - name: Join Blue Domain
      win_domain_membership:
        state: domain
        dns_domain_name: "{{ domain }}"
        domain_admin_user: "{{ domainadminuser }}"
        domain_admin_password: "{{ domainadminpass }}"
        domain_ou_path: OU=Workstations,OU=Computers,OU=blue8,DC=blue8,DC=local
      register: domain_join_state

    - name: Reboot after creation
      when: domain_join_state.reboot_required
      win_reboot:
        msg: "Domain Join in process; rebooting..."
        # Tests to see if Server Core is back up
        test_command: 'hostname'