#Playbook for adding DHCP Reservations for vyOS

- name: vyos net config
  hosts: vyos
  vars_prompt:
  - name: mapping_name
    prompt: "what is the hostname of the map target?"
    private: no

  - name: mac_address
    prompt: "what mac address are you going to map?"
    private: no
  - name: ip_address
    prompt: "what ip address are you going to map?"
    private: no
  tasks:
    - name: configure vyos dhcp static mapping
      vyos_config:
        save: yes
        lines:
        - set service dhcp-server shared-network-name '{{ shared_network }}' subnet '{{ lan }}' static-mapping '{{ mapping_name }}' ip-address '{{ ip_address }}'
        - set service dhcp-server shared-network-name '{{ shared_network }}' subnet '{{ lan }}' static-mapping '{{ mapping_name }}' mac-address '{{ mac_address }}'
